# Generated by Django 4.0.3 on 2022-10-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('IDKH', models.AutoField(primary_key=True, serialize=False)),
                ('TenKH', models.CharField(max_length=50)),
                ('GiaKH', models.BinaryField()),
                ('ThoiGian', models.DateTimeField()),
            ],
            options={
                'db_table': 'home_khoahoc',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('TenND', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'home_nguoidung',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('MatKhau', models.CharField(max_length=20)),
                ('TenND', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'home_taikhoan',
            },
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('IDBai', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('TenND', models.CharField(max_length=50)),
                ('TitleBai', models.CharField(max_length=500)),
                ('ContentBai', models.TextField(max_length=2000)),
                ('Ngay', models.DateTimeField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.taikhoan')),
            ],
            options={
                'db_table': 'home_baiviet',
            },
        ),
    ]
